'use strict';
const $=(s)=>document.querySelector(s); const raw=sessionStorage.getItem('vetlab_ultimo_reporte');
if(!raw){ $('#report-sheet').innerHTML='<p>No hay un reporte preparado.</p>'; $('.download-actions').hidden=true; }
else { const datos=JSON.parse(raw); render(datos); $('#descargar-pdf').addEventListener('click',()=>pdf(datos)); $('#descargar-word').addEventListener('click',()=>word(datos)); }
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function especie(d){return d.especie==='gato'?'Felino':'Canino';}
function fecha(v){const p=String(v||'').split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v;}
function archivo(d,ext){return `hemograma_${String(d.paciente||'sin_nombre').replace(/[^a-z0-9_-]+/gi,'_')}.${ext}`;}
function render(d){$('#titulo-paciente').textContent=d.paciente||'Paciente sin nombre';$('#titulo-especie').textContent=especie(d); const rows=d.filas.map(f=>`<tr><td>${esc(f.parametro)}</td><td>${esc(f.resultado)}</td><td>${esc(f.unidad)}</td><td>${esc(f.referencia)}</td><td class="${['Alto','Bajo'].includes(f.estado)?'abnormal':''}">${esc(f.estado)}</td></tr>`).join('');
$('#report-sheet').innerHTML=`<div class="report-brand"><div class="report-brand-left"><img src="./img/logo.jpg" class="logo-report" alt="Clínica Veterinaria Fortuna"><div><strong>CLÍNICA VETERINARIA FORTUNA</strong><span>Reporte de resultados</span></div></div><div class="report-brand-meta"><b>Reporte:</b> ${esc(d.reporte)}<br><b>Emisión:</b> ${esc(fecha(d.fecha))}</div></div><div class="report-info"><div><b>Datos del paciente</b><span>Paciente: ${esc(d.paciente)}</span><span>Propietario: ${esc(d.propietario)}</span><span>Especie: ${especie(d)}</span><span>Edad: ${esc(d.edad)}</span></div><div><b>Datos del reporte</b><span>Expediente: ${esc(d.expediente)}</span><span>Médico veterinario: ${esc(d.veterinario)}</span></div></div><div class="table-wrap"><table class="report-table"><thead><tr><th>Hemograma</th><th>Resultado</th><th>Unidad</th><th>Referencia</th><th>Observaciones</th></tr></thead><tbody>${rows}</tbody></table></div>${d.observaciones?`<p class="report-notes"><b>Observaciones:</b> ${esc(d.observaciones)}</p>`:''}`;}
async function logoData(){try{const r=await fetch('./img/logo.jpg');const b=await r.blob();return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(b);});}catch{return null;}}
async function pdf(d){const box=$('#estado-reporte');try{if(!window.jspdf)throw new Error('No se cargó el generador de PDF.'); const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'pt',format:'letter'});const azul=[20,85,107],teal=[23,121,151];const logo=await logoData(); if(logo)doc.addImage(logo,'JPEG',42,28,85,50);doc.setTextColor(...azul);doc.setFontSize(15);doc.setFont(undefined,'bold');doc.text('CLÍNICA VETERINARIA FORTUNA',145,46);doc.setFontSize(8);doc.setFont(undefined,'normal');doc.setTextColor(96,125,139);doc.text('Tel. 2979-9444 | vetfortuna@gmail.com | La Fortuna',145,61);doc.setTextColor(...azul);doc.setFontSize(17);doc.setFont(undefined,'bold');doc.text('REPORTE DE RESULTADOS',42,105);doc.setFontSize(8.5);doc.setFont(undefined,'normal');doc.setTextColor(31,41,55);doc.text(`Reporte: ${d.reporte}`,430,45);doc.text(`Emisión: ${fecha(d.fecha)}`,430,58);
const info=[['DATOS DEL PACIENTE','DATOS DEL REPORTE'],[`Paciente: ${d.paciente}\nPropietario: ${d.propietario}\nEspecie: ${especie(d)}\nEdad: ${d.edad}`,`Expediente: ${d.expediente}\nMédico veterinario: ${d.veterinario}`]];doc.autoTable({startY:120,body:info,theme:'grid',styles:{fontSize:8.5,cellPadding:7,valign:'top'},columnStyles:{0:{cellWidth:250},1:{cellWidth:250}},didParseCell:data=>{if(data.row.index===0){data.cell.styles.fillColor=[231,242,245];data.cell.styles.textColor=azul;data.cell.styles.fontStyle='bold';}}});
const body=d.filas.map(f=>[f.parametro,f.resultado,f.unidad,f.referencia,f.estado]);doc.autoTable({startY:doc.lastAutoTable.finalY+14,head:[['HEMOGRAMA','Resultado','Unidad','Referencia','Observaciones']],body,theme:'grid',headStyles:{fillColor:teal,textColor:255,fontStyle:'bold'},styles:{fontSize:8.5,cellPadding:5},didParseCell:data=>{if(data.section==='body'&&data.column.index===4&&['Alto','Bajo'].includes(String(data.cell.raw))){data.cell.styles.textColor=[180,35,24];data.cell.styles.fontStyle='bold';}}});let y=doc.lastAutoTable.finalY+18;if(d.observaciones){doc.setFontSize(8.5);doc.setTextColor(96,125,139);doc.text(`Observaciones: ${d.observaciones}`,42,y,{maxWidth:500});}doc.setFontSize(8);doc.text('Clínica Veterinaria Fortuna | Documento confidencial',306,755,{align:'center'});doc.save(archivo(d,'pdf'));}catch(e){box.hidden=false;box.className='status-box error';box.textContent=e.message||'No se pudo generar el PDF.';}}
function word(d){const rows=d.filas.map(f=>`<tr><td>${esc(f.parametro)}</td><td>${esc(f.resultado)}</td><td>${esc(f.unidad)}</td><td>${esc(f.referencia)}</td><td>${esc(f.estado)}</td></tr>`).join('');const html=`<!DOCTYPE html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;color:#1f2937}h1{color:#14556b;font-size:20px}table{border-collapse:collapse;width:100%;margin:14px 0}td,th{border:1px solid #cadde3;padding:7px;font-size:10pt}th{background:#177997;color:white}.meta td{background:#e7f2f5}</style></head><body><h1>CLÍNICA VETERINARIA FORTUNA</h1><p><b>REPORTE DE RESULTADOS</b><br>Reporte: ${esc(d.reporte)} · Emisión: ${esc(fecha(d.fecha))}</p><table class="meta"><tr><td><b>DATOS DEL PACIENTE</b><br>Paciente: ${esc(d.paciente)}<br>Propietario: ${esc(d.propietario)}<br>Especie: ${especie(d)}<br>Edad: ${esc(d.edad)}</td><td><b>DATOS DEL REPORTE</b><br>Expediente: ${esc(d.expediente)}<br>Médico veterinario: ${esc(d.veterinario)}</td></tr></table><table><tr><th>HEMOGRAMA</th><th>Resultado</th><th>Unidad</th><th>Referencia</th><th>Observaciones</th></tr>${rows}</table>${d.observaciones?`<p><b>Observaciones:</b> ${esc(d.observaciones)}</p>`:''}</body></html>`;const blob=new Blob(['\ufeff',html],{type:'application/msword'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=archivo(d,'doc');document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000);}
